---
# tasks file for dovecot

- name: Install Packages
  ansible.builtin.apt:
    name:
      - mailutils
      - dovecot-core
      - dovecot-imapd
    state: latest

- name: Dovecot Service
  ansible.builtin.service:
    name: dovecot
    state: started
    enabled: yes

# ------------------------------
# Key SSL Settings, most are defaults
#
# ssl = required
# ssl_cert = </etc/dovecot/private/dovecot.pem
# ssl_key = </etc/dovecot/private/dovecot.key
# ssl_client_ca_dir = /etc/ssl/certs
# ssl_dh = </usr/share/dovecot/dh.pem
# ------------------------------
- name: Require SSL for Dovecot
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-ssl.conf
    regexp: '^ssl ='
    line: 'ssl = required'
    backup: yes
  notify: Restart Dovecot

# ------------------------------
# Enable IMAPS Listener
# - Disable IMAP
#
# ------------------------------
- name: Enable IMAPS for Dovecot a
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-master.conf
    regexp: '^([^#]*)port = 143'
    line: g\<1>#port = 143
    backrefs: yes
    backup: yes
  notify: Restart Dovecot

- name: Enable IMAPS for Dovecot b
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-master.conf
    regexp: '^(.*)# *port = 993'
    line: g\<1>port = 993
    backrefs: yes
    backup: yes
  notify: Restart Dovecot

- name: Enable IMAPS for Dovecot c
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-master.conf
    regexp: '^(.*)# *ssl = yes'
    line: g\<1>ssl = yes
    backrefs: yes
    backup: yes
  notify: Restart Dovecot
