---
# tasks file for dovecot

- name: Install Packages
  ansible.builtin.apt:
    name:
      - mailutils
      - dovecot-core
      - dovecot-imapd
    state: latest

- name: Dovecot Service
  ansible.builtin.service:
    name: dovecot
    state: started
    enabled: yes

# ------------------------------
# Key SSL Settings, most are defaults
#
# ssl = required
# ssl_cert = </etc/dovecot/private/dovecot.pem
# ssl_key = </etc/dovecot/private/dovecot.key
# ssl_client_ca_dir = /etc/ssl/certs
# ssl_dh = </usr/share/dovecot/dh.pem
# ------------------------------
- name: Require SSL for Dovecot
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-ssl.conf
    regexp: '^ssl ='
    line: 'ssl = required'
    backup: yes
  notify: Restart Dovecot

# ------------------------------
# Enable IMAPS Listener
# - Disable IMAP
#
# ------------------------------
- name: Enable IMAPS for Dovecot
  ansible.builtin.copy:
    src: 10-master.conf
    dest: /etc/dovecot/conf.d/10-master.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: Restart Dovecot
