---
- hosts: all
  vars_files:
    - default.config.yml
  become: yes

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - common
    - openssh
    - dovecot
