---
- hosts: all
  vars_files:
    - default.config.yml
    - config.yml
  become: true

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: common
    - role: openssh
    - role: dovecot
      tags:
        - dovecot
    - role: duplicati
      tags:
        - duplicati
      vars:
        desired_version: "2.1.0.106_canary_2025-01-11"
