---
- hosts: all
  vars_files:
    - default.config.yml
    - config.yml
  become: yes

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: common
    - role: openssh
    - role: dovecot
      tags:
        - dovecot
