---
# tasks file for duplicati
- name: Create /mnt_rw
  ansible.builtin.file:
    path: /mnt_rw
    state: directory

- name: Mount /mnt_rw on tmpfs
  ansible.posix.mount:
    path: /mnt_rw
    src: tmpfs
    fstype: tmpfs
    opts: size=20m
    state: mounted

- name: Change /mnt to RO bind mount
  ansible.posix.mount:
    path: /mnt
    src: /mnt_rw
    fstype: none
    opts: bind,ro
    state: mounted

- name: Install smbcredentials
  ansible.builtin.copy:
    src: smbcredentials
    dest: /home/asterr/.smbcredentials
    owner: asterr
    group: asterr
    mode: u=rw,g-rwx,o-rwx
    backup: yes

- name: Install cifs-utils
  ansible.builtin.apt:
    name: cifs-utils
    state: latest

- name: Install Mono
  ansible.builtin.apt:
    name:
      - mono-complete
    state: latest

- name: Ensure downloads directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Downloads"
    state: directory

- name: Fetch Duplicati Package
  ansible.builtin.get_url:
    url: https://github.com/duplicati/duplicati/releases/download/v2.0.9.100_canary_2024-05-30/duplicati-2.0.9.100_canary_2024-05-30-linux-arm64-cli.deb
    dest: "{{ ansible_env.HOME }}/Downloads/duplicati-2.0.9.100_canary_2024-05-30-linux-arm64-cli.deb"

- name: Install Duplicati Package
  ansible.builtin.apt:
    deb: "{{ ansible_env.HOME }}/Downloads/duplicati-2.0.9.100_canary_2024-05-30-linux-arm64-cli.deb"

- name: Duplicati Service
  ansible.builtin.service:
    name: duplicati
    state: started
    enabled: yes

- name: Create duplicati001 mount point
  ansible.builtin.file:
    path: /mnt_rw/duplicati001
    state: directory

- name: Create duplicati002 mount point
  ansible.builtin.file:
    path: /mnt_rw/duplicati002
    state: directory

- name: Mount duplicati001 disk
  ansible.posix.mount:
    path: /mnt/duplicati001
    src: //192.168.2.143/duplicati001
    fstype: cifs
    opts: credentials=/home/asterr/.smbcredentials,iocharset=utf8,cache=none,vers=1.0
    state: mounted

- name: Mount duplicati002 disk
  ansible.posix.mount:
    path: /mnt/duplicati002
    src: //192.168.2.144/duplicati002
    fstype: cifs
    opts: credentials=/home/asterr/.smbcredentials,iocharset=utf8,cache=none,vers=1.0
    state: mounted
