---
# tasks file for duplicati
- name: Create /mnt_rw
  ansible.builtin.file:
    path: /mnt_rw
    state: directory

- name: Mount /mnt_rw on tmpfs
  ansible.posix.mount:
    path: /mnt_rw
    src: tmpfs
    fstype: tmpfs
    opts: size=20m
    state: mounted

- name: Change /mnt to RO bind mount
  ansible.posix.mount:
    path: /mnt
    src: /mnt_rw
    fstype: none
    opts: bind,ro
    state: mounted

- name: Install smbcredentials
  ansible.builtin.copy:
    src: smbcredentials
    dest: /home/asterr/.smbcredentials
    owner: asterr
    group: asterr
    mode: u=rw,g-rwx,o-rwx
    backup: yes

- name: Install cifs-utils
  ansible.builtin.apt:
    name: cifs-utils
    state: latest

- name: Install Mono
  ansible.builtin.apt:
    name:
      - mono-complete
    state: latest

- name: Install Duplicati
  ansible.builtin.apt:
    deb: >
      https://github.com/duplicati/duplicati/releases/download/
      v2.0.6.104-2.0.6.104_canary_2022-06-15/duplicati_2.0.6.104-1_all.deb

- name: Duplicati Service
  ansible.builtin.service:
    name: duplicati
    state: started
    enabled: yes
