---
# tasks file for common

- name: Setup timezone to Asia/Tokyo
  ansible.builtin.timezone:
    name: Asia/Tokyo

- name: Install Git
  ansible.builtin.apt:
    name: git
    state: latest

- name: Install Aptitude
  ansible.builtin.apt:
    name: aptitude
    state: latest

# -----------------------------
# Set my hostname
#
- name: Set a hostname
  ansible.builtin.hostname:
    name: zeus

- name: Add name to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: 127.0.0.1 localhost zeus
    owner: root
    group: root
    mode: '0644'
    backup: 'yes'

# -----------------------------
# Set locale
#
- name: Set Locale to English
  ansible.builtin.include_role:
    name: debops.debops.locales
    apply:
      tags:
        - locale
  vars:
    locales__system_lang: 'en_US.UTF-8'
    locales__list:
      - name: en_US.UTF-8
        state: present
      - name: ja_JP.UTF-8
        state: absent

  tags:
    - always


# -----------------------------
# Install apt
#
- name: Install Pip
  ansible.builtin.apt:
    name: python3-pip
    state: latest

- name: Install software properties common
  ansible.builtin.apt:
    name: software-properties-common
    state: latest

- name: Add ansible repository from PPA
  ansible.builtin.apt_repository:
    repo: ppa:ansible/ansible

- name: Install ansible
  ansible.builtin.apt:
    name: ansible
    state: latest

- name: Install passlib
  ansible.builtin.apt:
    name: python3-passlib
    state: latest

# End Install apt
#
# -----------------------------


# -----------------------------
# Setup user
#
- name: Install user packages
  ansible.builtin.apt:
    name:
      - whois
    state: latest

- name: Create Group asterr
  ansible.builtin.group:
    name: asterr
    gid: 1000
    state: present

- name: Create User asterr
  ansible.builtin.user:
    name: asterr
    comment: Aaron Sterr
    uid: 1000
    groups: ['asterr', 'sudo']
    home: '/home/asterr'
    password_expire_max: 99999
    password_expire_min: 0
    shell: /bin/bash

- name: Create Group uroot
  ansible.builtin.group:
    name: uroot
    gid: 1001
    state: present

- name: Create User uroot
  ansible.builtin.user:
    name: uroot
    comment: Ubuntu Root
    uid: 1001
    group: uroot
    groups: ['uroot', 'sudo']
    home: '/home/uroot'
    password: "{{ '%s' | format(uroot_password) | regex_replace('\n', '') | password_hash('sha512') }}"
    update_password: on_create
    password_expire_max: 99999
    password_expire_min: 0
    shell: /bin/bash
  tags:
    - user

# -----------------------------
# Cron to run ansible
#
- name: Install wrapper
  ansible.builtin.copy:
    src: ansible-runner.sh
    dest: /home/asterr/ansible-runner.sh
    mode: u=rwx,g=rx,o=rx
    backup: yes

- name: Add ansible cron job
  ansible.builtin.cron:
    name: "run ansible"
    minute: "*/15"
    job: "if ! out=`/home/asterr/ansible-runner.sh 2>&1`; then echo \"$out\"; fi"
    backup: yes
    user: asterr
