---
# tasks file for common

- name: Setup timezone to Asia/Tokyo
  ansible.builtin.timezone:
    name: Asia/Tokyo
    state: latest

- name: Install Git
  ansible.builtin.apt:
    name: git
    state: latest

- name: Install Pip
  ansible.builtin.apt:
    name: python3-pip
    state: latest

- name: Install software properties common
  ansible.builtin.apt:
    name: software-properties-common
    state: latest

- name: Add ansible repository from PPA
  ansible.builtin.apt_repository:
    repo: ppa:ansible/ansible

- name: Install ansible
  ansible.builtin.apt:
    name: ansible
    state: latest

